--- a/ipheth-pair/Makefile
+++ b/ipheth-pair/Makefile
@@ -1,14 +1,12 @@
-CFLAGS += -Wall -O2
-LDLIBS += -limobiledevice
+LDLIBS += -limobiledevice-1.0
 
 all: ipheth-pair
 
 ipheth-pair: ipheth-pair.o
 
 install:
-	install -m 0755 ipheth-pair /lib/udev/
-	install -m 0644 90-iphone-tether.rules /etc/udev/rules.d
-	/sbin/udevadm control --reload-rules
+	install -D -m 0755 ipheth-pair ${DESTDIR}/usr/bin/ipeth-pair
+	install -D -m 0644 90-iphone-tether.rules ${DESTDIR}/${UDEV_RULES_PATH}/rules.d/90-iphone-tether.rules
 
 clean:
 	rm -f *.o ipheth-pair
