#!/bin/sh
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id: e493a7bf35f4df5cb42acd0fa16435fddd94f3d0 $

if [ -e ./env ] ; then source ./env ; else echo "failed to source env" ; fi
exec "${basedir}/sbin/mysqld" --defaults-file="${MY_CNF}" ${MY_ARGS} 2>&1
