--- Makefile.dist	2011-08-16 15:02:44.128755738 +0100
+++ Makefile	2011-08-16 15:06:03.346319737 +0100
@@ -1,18 +1,25 @@
 
+CC = gcc
+LD = ld
+CFLAGS = -Os -march=pentium4 -mfpmath=sse -mmmx -msse -msse2 -fomit-frame-pointer -pipe
+LDFLAGS = -O1 --as-needed
+OPT = -D_TRACE_ -Wall
+
 all:	pam_mobile_otp.so
 
 debug:
-	OPTS="-D_TRACE_ -Wall" make all
+	OPT = -D_TRACE_ -Wall
+	pam_mobile_otp.so
 
 pam_mobile_otp.o	: pam_mobile_otp.c
-	gcc -fPIC -c pam_mobile_otp.c
+	$(CC) $(CFLAGS) $(OPT) -fPIC -c pam_mobile_otp.c
 
 pam_mobile_otp.so	: pam_mobile_otp.o md5.o
-	ld -x --shared -o pam_mobile_otp.so pam_mobile_otp.o \
+	$(LD) $(LDFLAGS) -x --shared -o pam_mobile_otp.so pam_mobile_otp.o \
 		md5.o -lpam
 
 md5.o	: md5.c
-	gcc -fPIC -c md5.c -DSTDC_HEADERS
+	$(CC) $(CFLAGS) $(OPT) -fPIC -c md5.c -DSTDC_HEADERS
 
 install	: pam_mobile_otp.so
 	cp pam_mobile_otp.so /lib/security/pam_mobile_otp.so
