#! /bin/sh

set -u

[ -f "/proc/ide/${MDEV}/media" ] || exit 1

media="$( cat "/proc/ide/${MDEV}/media" )"
for i in "${media}" "${media}"[0-9]* ; do
	if [ "$( readlink "$i" 2>/dev/null )" = "${MDEV}" ] ; then
		LINK="${i}"
		break
	fi
done

# Link exists, remove if necessary and exit
if [ -n "${LINK:-}" ] ; then
	[ "${ACTION:-}" = 'remove' ] && rm "${LINK}"
	exit
fi

# Create a link
# shellcheck disable=SC2012
num="$( ls "${media}"[0-9]* 2>/dev/null | wc -l )"
ln -sf "${MDEV}" "${media}${num}"

[ -e "${media}" ] || ln -sf "${MDEV}" "${media}"

