#!/bin/sh

set -u

# env ACTION=... DEVPATH=... SUBSYSTEM=... [SEQNUM=...]

LOGFILE="mdev.log"
#ENV="$( env )"
DATE="$( date +"%s %T.%N" )"

# shellcheck disable=SC2116
fmtstr="$( echo \
		"%d %s mdev_debug invoked as '%s' in '%s'," \
		"MDEV '%s', ACTION '%s', BUSNUM '%d'," \
		"DEVNUM '%d', DEVNAME '%s', DEVPATH '%s', DEVTYPE '%s'," \
		"SUBSYSTEM '%s', MODALIAS '%s', FIRMWARE '%s'," \
		"MAJOR '%d', MINOR '%d', TYPE '%s', PRODUCT '%s'," \
		"INTERFACE '%s', SEQNUM '%d'"
	)"

# shellcheck disable=SC2059
printf >>"${LOGFILE}" "${fmtstr}\\n" \
	"${$}" \
	"${DATE}" \
	"${0}" \
	"$( pwd )" \
	"${MDEV:-}" \
	"${ACTION:-}" \
	"${BUSNUM:-"-1"}" \
	"${DEVNUM:-"-1"}" \
	"${DEVNAME:-}" \
	"${DEVPATH:-}" \
	"${DEVTYPE:-}" \
	"${SUBSYSTEM:-}" \
	"${MODALIAS:-}" \
	"${FIRMWARE:-}" \
	"${MAJOR:-"-1"}" \
	"${MINOR:-"-1"}" \
	"${TYPE:-}" \
	"${PRODUCT:-}" \
	"${INTERFACE:-}" \
	"${SEQNUM:-"-1"}"
# "\n---\n${ENV}\n..."

exit 0
