#!/bin/sh

# env ACTION=... DEVPATH=... SUBSYSTEM=... [SEQNUM=...]

LOGFILE="mdev.log"
#ENV="$( env )"
DATE="$( date +"%s %T.%N" )"

echo -e >>"${LOGFILE}" "${$} ${DATE} mdev_debug invoked as '$0' in '$( pwd )', MDEV '$MDEV', ACTION '$ACTION', BUSNUM '$BUSNUM', DEVNUM '$DEVNUM', DEVNAME '$DEVNAME', DEVPATH '$DEVPATH', DEVTYPE '$DEVTYPE', SUBSYSTEM '$SUBSYSTEM', MODALIAS '$MODALIAS', FIRMWARE '$FIRMWARE', MAJOR '$MAJOR', MINOR '$MINOR', TYPE '$TYPE', PRODUCT '$PRODUCT', INTERFACE '$INTERFACE', SEQNUM '$SEQNUM'" # "\n---\n${ENV}\n..."

exit 0
