#! /bin/sh

set -u

# env ACTION=... DEVPATH=... SUBSYSTEM=... [SEQNUM=...]

LOGFILE="mdev.log"
ENV="$( env )"
DATE="$( date +"%s %T.%N" )"

# shellcheck disable=SC2116
fmtstr="$( echo \
		"%s %s mdev_nomatch invoked as '%s' in '%s'," \
		"MDEV '%s', ACTION '%s', DEVPATH '%s', SUBSYSTEM '%s'," \
		"SEQNUM '%d'"
	)"

# shellcheck disable=SC2012
printf >>"${LOGFILE}" "${fmtstr}\\n---\\n%s\\n---\\n%s\\n...\\n" \
	"${$}" \
	"${DATE}" \
	"${0}" \
	"$( pwd )" \
	"${MDEV:-}" \
	"${ACTION:-}" \
	"${DEVPATH:-}" \
	"${SUBSYSTEM:-}" \
	"${SEQNUM:-"-1"}" \
	"${ENV:-}" \
	"$( ls -lt /dev/ | head -n 6 | tail -n 3 )"

exit 0
