#! /bin/sh

set -u

# NOTE: since mdev -s only provides $MDEV, don't depend on any hotplug vars.

current="$( readlink usbdisk 2>/dev/null )"

if [ "${current:-}" = "${MDEV:-}" ] && [ "${ACTION:-}" = 'remove' ]; then
	rm -f usbdisk usba1 
fi
[ -n "${current:-}" ] && exit 0

if [ -e "/sys/block/${MDEV}" ]; then
	SYSDEV="$( readlink -f "/sys/block/${MDEV}/device" 2>/dev/null )"

	# If /sys device path contains '/usb[0-9]' then we assume it's usb and also
	# if it's a usb without partitions we require FAT
	if [ "${SYSDEV##*/usb[0-9]}" != "${SYSDEV}" ]; then
		if command -v strings >/dev/null 2>&1; then
			# Do not create link if there is not FAT
			dd if="/dev/${MDEV}" bs=512 count=1 2>/dev/null |
				strings |
				grep FAT >/dev/null || exit 0
		fi

		ln -sf "${MDEV}" usbdisk
		# Keep this for backwards compatibility: people have it in fstab
		ln -sf "${MDEV}" usba1
	fi

else
	for i in /sys/block/*/"${MDEV}"; do
		if [ -e "${i}" ]; then
			PARENT="$( dirname "${i}" )"
			SYSDEV="$( readlink -f "${PARENT}/device" )"
			if [ "${SYSDEV##*/usb[0-9]}" != "${SYSDEV}" ]; then
				ln -sf "${MDEV}" usbdisk
				# Keep this also for backwards compatibility
				ln -sf "${MDEV}" usba1
			fi
		fi
	done
fi

exit 0
